### ISSUE TITLE
This macro should probably be redirected to FreeCAD/FreeCAD-macros

### ISSUE THREAD

**Issue by luzpaz** [easyw/FreeCAD_Macros#1]
The FreeCAD wiki page: https://www.freecadweb.org/wiki/Macro_Center_Align_Objects_with_Faces_or_Edges
points to this repository. 

Obviously, this macro has been superseded by the Manipulator WB, But principally, it makes sense to move it to the https://github.com/FreeCAD/FreeCAD-macros instead of hosting it on a 3rd party repo.

**Comment by easyw** [comment]
> Obviously, this macro has been superseded by the Manipulator WB, But principally, it makes sense to move it to the https://github.com/FreeCAD/FreeCAD-macros instead of hosting it on a 3rd party repo.

@lupaz the reason why the macro is on this repo is related to the fact that once the macros were stored in the wiki pages... My macro, as some others, has too many characters to be hosted in the wiki page (wiki characters limitation), then I hosted in my repo.
ATM this code has been superseded by the Manipulator WB and it is not maintained...
Feel free to update the wiki accordingly.

**Comment by luzpaz** [comment]
CC @galou shall we move the macro to https://github.com/FreeCAD/FreeCAD-macros then ?

**Comment by galou** [comment]
I don't think we should add a macro which is declared as unmaintained and for which a better solution exists.
